version: '3.7'

services:
  backend:
    # depends_on:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8080:8080"

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000" 
  nginx:
        depends_on:
          - backend
          - frontend
        restart: always
        build:
            context: ./nginx
        ports:
            - "5001:5001"
volumes: 
  db:

networks:
  backend:
  frontend: